import turtle
t = turtle.Turtle(shape="turtle")
t.pensize(10)
t.circle(50)
t.color("blue")
t.pensize(10)
t.penup()
t.setposition(-120, 0)
t.pendown()
t.circle(50)
t.color("green")
t.pensize(10)

t.penup()
t.setposition(60, 60)
t.pendown()
t.circle(50)
t.color("yellow")
t.pensize(10)

t.penup()
t.setposition(-60, 60)
t.pendown()
t.circle(50)
t.color("red")
t.pensize(10)
t.penup()
t.setposition(-180, 60)
t.pendown()

t.circle(50)
t.color("pink")
t.pensize(10)
turtle.done()